# Generated by Django 4.2.4 on 2023-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='habitats',
            field=models.ManyToManyField(to='main_app.habitat'),
        ),
    ]
